var themeTitle = "<TABLE width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><TR><TD background=\"bg-tile-1.jpg\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/bg-tile.jpg*/><IMG src=\"masthead-1.jpg\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/masthead.jpg*/ width=\"306\" height=\"60\" NAME=\"IGNORE\"></TD></TR><TR><TD align=center><H1>%s</H1></TD></TR></TABLE>"
var themeSubTitle = "%s"
var themeURL = "<A HREF=\"%s\"><IMG src=\"home-button-1.gif\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/home-button.gif*/ width=\"33\" height=\"31\" NAME=\"IGNORE\" alt=\"%s\"></A>"
var themeThumbLinkPrevious = ""
var themeThumbLinkNext = ""
var themeThumbLinkPlay = ""
var themeThumbLinkStop = ""
var themeThumbLink = "<A HREF=\"page-1.htm-%s,%s.htm\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/page.htm?%s,%s*/ target=\"Top Frame\"><IMG></A>"
var themeImageLinkPrevious = "<A HREF=\"page-1.htm-%s,%s.htm\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/page.htm?%s,%s*/ target=\"Top Frame\"><IMG src=\"previous-button-1.gif\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/previous-button.gif*/ width=\"33\" height=\"31\" NAME=\"IGNORE\"></A>"
var themeImageLinkNext = "<A HREF=\"page-1.htm-%s,%s.htm\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/page.htm?%s,%s*/ target=\"Top Frame\"><IMG src=\"next-button-1.gif\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/next-button.gif*/ width=\"33\" height=\"31\" NAME=\"IGNORE\"></A>"
var themeImageLinkPlay = "<A HREF=\"javascript:void(0)\" name=slideShowControl onclick=\"stopStartSlideShow()\"><IMG src=\"play-button-1.gif\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/play-button.gif*/ width=\"33\" height=\"31\" NAME=\"IGNORE\"></a>"
var themeImageLinkStop = "<A HREF=\"javascript:void(0)\" name=slideShowControl onclick=\"stopStartSlideShow()\"><IMG src=\"stop-button-1.gif\"/*tpa=http://www.cme-pro.com/endorser/Interface/pics/Data/stop-button.gif*/ width=\"33\" height=\"31\" NAME=\"IGNORE\"></a>"
var themeImageLink = "<IMG>"